#!/usr/bin/env python3
"""gen.py OUTDIR: writes OUTDIR/driver.s (the PowerPC side of check.sh) and
OUTDIR/table.h (the host side), from the list of test cases below.

A record (big-endian) is: u32 case, u32 aux, 32 floats in[0..31]; the result
is 16 words out[0..15] (the output buffer, filled with 0x13579bdf first) and
a return word (r3, or f1 stored as a float). Arguments: O is the output
buffer, In a pointer to in[n], fn the float in[n], aux the aux word; copy
(a, b) copies in[a..b-1] to the output buffer first (in-place cases)."""
import os, sys

CASES = [
    # name, function, return, args, copy
    ('Identity', 'PSMTXIdentity', None, ['O'], None),
    ('Copy', 'PSMTXCopy', None, ['I0', 'O'], None),
    ('Concat', 'PSMTXConcat', None, ['I0', 'I12', 'O'], None),
    ('Concat_ab=a', 'PSMTXConcat', None, ['O', 'I12', 'O'], (0, 12)),
    ('Concat_ab=b', 'PSMTXConcat', None, ['I0', 'O', 'O'], (12, 24)),
    ('Inverse', 'PSMTXInverse', 'u', ['I0', 'O'], None),
    ('Inverse_inplace', 'PSMTXInverse', 'u', ['O', 'O'], (0, 12)),
    ('RotRad', 'PSMTXRotRad', None, ['O', 'aux', 'f0'], None),
    ('RotTrig', 'PSMTXRotTrig', None, ['O', 'aux', 'f0', 'f1'], None),
    ('RotAxisRad', 'PSMTXRotAxisRad', None, ['O', 'I0', 'f3'], None),
    ('Trans', 'PSMTXTrans', None, ['O', 'f0', 'f1', 'f2'], None),
    ('TransApply', 'PSMTXTransApply', None, ['I0', 'O', 'f12', 'f13', 'f14'], None),
    ('TransApply_inplace', 'PSMTXTransApply', None, ['O', 'O', 'f12', 'f13', 'f14'], (0, 12)),
    ('Scale', 'PSMTXScale', None, ['O', 'f0', 'f1', 'f2'], None),
    ('ScaleApply', 'PSMTXScaleApply', None, ['I0', 'O', 'f12', 'f13', 'f14'], None),
    ('ScaleApply_inplace', 'PSMTXScaleApply', None, ['O', 'O', 'f12', 'f13', 'f14'], (0, 12)),
    ('Quat', 'PSMTXQuat', None, ['O', 'I0'], None),
    ('LookAt', 'C_MTXLookAt', None, ['O', 'I0', 'I3', 'I6'], None),
    ('LightFrustum', 'C_MTXLightFrustum', None, ['O'] + ['f%d' % i for i in range(9)], None),
    ('LightPerspective', 'C_MTXLightPerspective', None, ['O'] + ['f%d' % i for i in range(6)], None),
    ('LightOrtho', 'C_MTXLightOrtho', None, ['O'] + ['f%d' % i for i in range(8)], None),
    ('Perspective', 'C_MTXPerspective', None, ['O'] + ['f%d' % i for i in range(4)], None),
    ('Ortho', 'C_MTXOrtho', None, ['O'] + ['f%d' % i for i in range(6)], None),
    ('Frustum*', 'C_MTXFrustum', None, ['O'] + ['f%d' % i for i in range(6)], None),
    ('MultVec', 'PSMTXMultVec', None, ['I0', 'I12', 'O'], None),
    ('MultVec_inplace', 'PSMTXMultVec', None, ['I0', 'O', 'O'], (12, 15)),
    ('MultVecArray', 'PSMTXMultVecArray', None, ['I0', 'I12', 'O', 'aux'], None),
    ('MultVecArray_inplace', 'PSMTXMultVecArray', None, ['I0', 'O', 'O', 'aux'], (12, 27)),
    ('MultVecSR', 'PSMTXMultVecSR', None, ['I0', 'I12', 'O'], None),
    ('VECAdd', 'PSVECAdd', None, ['I0', 'I3', 'O'], None),
    ('VECSubtract', 'PSVECSubtract', None, ['I0', 'I3', 'O'], None),
    ('VECScale', 'PSVECScale', None, ['I0', 'O', 'f3'], None),
    ('VECNormalize', 'PSVECNormalize', None, ['I0', 'O'], None),
    ('VECNormalize_inplace', 'PSVECNormalize', None, ['O', 'O'], (0, 3)),
    ('VECMag', 'PSVECMag', 'f', ['I0'], None),
    ('VECDotProduct', 'PSVECDotProduct', 'f', ['I0', 'I3'], None),
    ('VECCrossProduct', 'PSVECCrossProduct', None, ['I0', 'I3', 'O'], None),
    ('VECCrossProduct_c=a', 'PSVECCrossProduct', None, ['O', 'I3', 'O'], (0, 3)),
    ('VECSquareDistance', 'PSVECSquareDistance', 'f', ['I0', 'I3'], None),
    ('VECDistance', 'PSVECDistance', 'f', ['I0', 'I3'], None),
]
REC, RES, BATCH = 136, 68, 128

out = sys.argv[1]
s = []
e = s.append
e('''# Generated by tools/mtxmath/gen.py: reads records from stdin in batches, runs
# each case, writes the results to stdout.
	.section .text
	.globl _start
_start:
	lis r2, _SDA2_BASE_@ha
	addi r2, r2, _SDA2_BASE_@l
	lis r13, _SDA_BASE_@ha
	addi r13, r13, _SDA_BASE_@l
	stwu r1, -64(r1)
	lis r14, __ctors_start@ha
	addi r14, r14, __ctors_start@l
	lis r15, __ctors_end@ha
	addi r15, r15, __ctors_end@l
1:	cmplw r14, r15
	bge batch
	lwz r12, 0(r14)
	mtctr r12
	bctrl
	addi r14, r14, 4
	b 1b
batch:
	li r20, 0                    # bytes read
2:	li r0, 3
	li r3, 0
	lis r4, inbuf@ha
	addi r4, r4, inbuf@l
	add r4, r4, r20
	li r5, %d
	subf r5, r20, r5
	sc
	cmpwi r3, 0
	ble 3f
	add r20, r20, r3
	cmpwi r20, %d
	blt 2b
3:	li r21, %d
	divwu r22, r20, r21          # records in this batch
	cmpwi r22, 0
	beq done
	lis r14, inbuf@ha
	addi r14, r14, inbuf@l
	lis r15, outbuf@ha
	addi r15, r15, outbuf@l
	mr r23, r22
rec:	lis r0, 0x1357
	ori r0, r0, 0x9bdf
	li r3, 16
	mtctr r3
	addi r4, r15, -4
4:	stwu r0, 4(r4)
	bdnz 4b
	li r0, 0
	stw r0, 64(r15)
	lwz r16, 0(r14)
	lis r12, cases@ha
	addi r12, r12, cases@l
	slwi r16, r16, 2
	lwzx r12, r12, r16
	mtctr r12
	bctrl
	addi r14, r14, %d
	addi r15, r15, %d
	addic. r23, r23, -1
	bne rec
	li r0, 4                     # write the batch
	li r3, 1
	lis r4, outbuf@ha
	addi r4, r4, outbuf@l
	mulli r5, r22, %d
	sc
	cmpwi r20, %d
	beq batch
done:
	li r0, 1
	li r3, 0
	sc
''' % (REC * BATCH, REC * BATCH, REC, REC, RES, RES, REC * BATCH))


def lfs_fill(reg, off, base):
    e(f'\tlfs f{reg}, {off}({base})')
    e('\tlis r12, ps1_shadow@ha')
    e('\taddi r12, r12, ps1_shadow@l')
    e(f'\tstfd f{reg}, {8 * reg}(r12)')


for n, (name, fn, ret, args, copy) in enumerate(CASES):
    e(f'case{n}:\t# {name}')
    e('\tmflr r0')
    e('\tstw r0, 4(r1)')
    e('\tstwu r1, -32(r1)')
    if copy:
        for k in range(copy[0], copy[1]):
            e(f'\tlwz r0, {8 + 4 * k}(r14)')
            e(f'\tstw r0, {4 * (k - copy[0])}(r15)')
    gpr, fpr = 3, 1
    for a in args:
        if a == 'O':
            e(f'\tmr r{gpr}, r15')
            gpr += 1
        elif a == 'aux':
            e(f'\tlwz r{gpr}, 4(r14)')
            gpr += 1
        elif a[0] == 'I':
            e(f'\taddi r{gpr}, r14, {8 + 4 * int(a[1:])}')
            gpr += 1
        elif fpr <= 8:
            lfs_fill(fpr, 8 + 4 * int(a[1:]), 'r14')
            fpr += 1
        else:  # the ninth float argument goes to the parameter area
            e(f'\tlwz r0, {8 + 4 * int(a[1:])}(r14)')
            e('\tstw r0, 8(r1)')
    e(f'\tbl {fn}')
    if ret == 'u':
        e('\tstw r3, 64(r15)')
    elif ret == 'f':
        e('\tstfs f1, 64(r15)')
    e('\tlwz r0, 36(r1)')
    e('\taddi r1, r1, 32')
    e('\tmtlr r0')
    e('\tblr')
e('\t.section .data')
e('\t.balign 4')
e('cases:')
for n in range(len(CASES)):
    e(f'\t.4byte case{n}')
e('\t.section .bss')
e('\t.balign 8')
e(f'inbuf:\t.space {REC * BATCH}')
e(f'outbuf:\t.space {RES * BATCH}')
open(os.path.join(out, 'driver.s'), 'w').write('\n'.join(s) + '\n')

# host side
h = ['/* Generated by tools/mtxmath/gen.py */']
protos = set()
for name, fn, ret, args, copy in CASES:
    params = []
    for a in args:
        params.append('void*' if a in ('O',) or a[0] == 'I' else
                      ('unsigned' if fn == 'PSMTXMultVecArray' else 'char') if a == 'aux' else 'float')
    r = {'u': 'unsigned', 'f': 'float', None: 'void'}[ret]
    protos.add(f'{r} {fn}({", ".join(params)});')
h += sorted(protos)
h.append(f'#define NCASES {len(CASES)}')
h.append('static const char* case_names[] = { %s };' % ', '.join('"%s"' % c[0] for c in CASES))
h.append('static void run_case(unsigned n, unsigned aux, const float* in, float* out, unsigned* ret)')
h.append('{')
h.append('\tswitch (n) {')
for n, (name, fn, ret, args, copy) in enumerate(CASES):
    h.append(f'\tcase {n}:')
    if copy:
        h.append(f'\t\tmemcpy(out, in + {copy[0]}, {4 * (copy[1] - copy[0])});')
    cargs = []
    for a in args:
        cargs.append('out' if a == 'O' else 'aux' if a == 'aux' else f'(void*)(in + {a[1:]})' if a[0] == 'I'
                     else f'in[{a[1:]}]')
    call = f'{fn}({", ".join(cargs)})'
    if ret == 'u':
        h.append(f'\t\t*ret = {call};')
    elif ret == 'f':
        h.append(f'\t\t{{ float r = {call}; memcpy(ret, &r, 4); }}')
    else:
        h.append(f'\t\t{call};')
    h.append('\t\tbreak;')
h.append('\t}')
h.append('}')
open(os.path.join(out, 'table.h'), 'w').write('\n'.join(h) + '\n')
