// Generated by tools/mods/shi_layout/offsets.py: where the port keeps the members
// code mods address by retail offset, SMS_OFFSET(Class, retail offset).
#pragma once

#if defined(__LP64__)
#define SMS_OFFSET_ARCH(retail, p32, p64) (p64)
#else
#define SMS_OFFSET_ARCH(retail, p32, p64) (p32)
#endif


template <class T, unsigned long Retail> struct sms_offset_t;
#define SMS_OFFSET(cls, off) (sms_offset_t<cls, off>::value)

