// Generated by tools/mods/shi_layout/offsets.py: where the port keeps the members
// code mods address by retail offset. SMS_OFFSET(Class, retail offset) is a constant;
// a class and offset not in this table does not compile.
#pragma once

struct sms_offset_entry {
    const char *cls;
    unsigned long retail, p32, p64;
};

inline constexpr sms_offset_entry sms_offset_table[] = {
};

void sms_offset_not_in_table();  // not constexpr: an unknown entry fails to compile

consteval bool sms_offset_same(const char *a, const char *b) {
    while (*a && *a == *b) ++a, ++b;
    return *a == *b;
}

consteval unsigned long sms_offset_lookup(const char *cls, unsigned long retail) {
    for (const sms_offset_entry &e : sms_offset_table)
        if (e.retail == retail && sms_offset_same(e.cls, cls))
#if defined(__LP64__)
            return e.p64;
#else
            return e.p32;
#endif
    sms_offset_not_in_table();
    return 0;
}

#define SMS_OFFSET(cls, off) (sms_offset_lookup(#cls, off))
